-- MySQL Script generated by MySQL Workbench
-- Sun Feb 21 23:07:46 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema crm_app_myclass
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema crm_app_myclass
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `crm_app_myclass` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `crm_app_myclass` ;

-- -----------------------------------------------------
-- Table `crm_app_myclass`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm_app_myclass`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `description` VARCHAR(500) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `crm_app_myclass`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm_app_myclass`.`status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `crm_app_myclass`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm_app_myclass`.`task` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `startDate` VARCHAR(255) NOT NULL,
  `endDate` VARCHAR(255) NOT NULL,
  `createUserID` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `crm_app_myclass`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm_app_myclass`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(36) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `password` VARCHAR(500) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `address` VARCHAR(500) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `fullname` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `phone` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `roleId` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `FK_USER_ROLE` (`roleId` ASC) VISIBLE,
  CONSTRAINT `FK_USER_ROLE`
    FOREIGN KEY (`roleId`)
    REFERENCES `crm_app_myclass`.`role` (`id`),
  CONSTRAINT `user_ibfk_1`
    FOREIGN KEY (`roleId`)
    REFERENCES `crm_app_myclass`.`role` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `crm_app_myclass`.`task_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm_app_myclass`.`task_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `startDate` VARCHAR(100) NOT NULL,
  `endDate` VARCHAR(100) NOT NULL,
  `statusID` INT NOT NULL,
  `userID` INT NOT NULL,
  `taskID` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `FK_TC_T` (`taskID` ASC) VISIBLE,
  INDEX `FK_TC_S` (`statusID` ASC) VISIBLE,
  INDEX `FK_TC_U` (`userID` ASC) VISIBLE,
  CONSTRAINT `FK_TC_S`
    FOREIGN KEY (`statusID`)
    REFERENCES `crm_app_myclass`.`status` (`id`),
  CONSTRAINT `FK_TC_T`
    FOREIGN KEY (`taskID`)
    REFERENCES `crm_app_myclass`.`task` (`id`),
  CONSTRAINT `FK_TC_U`
    FOREIGN KEY (`userID`)
    REFERENCES `crm_app_myclass`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
